### ISSUE TITLE
docker build wokrs, but api do fail

### ISSUE THREAD

**Issue by Dexus** [cathaypacific8747/am4#10]
```
INFO:     202.61.224.44:36726 - "GET /ac_route/info?origin=iata%3AJFK&destination=iata%3AMUC&ac=name%3AB737-800&config_algorithm=AUTO&tpd_mode=STRICT_ALLOW_MULTIPLE_AC&trips_per_day_per_ac=4&sort_by=PER_AC_PER_DAY&realism=false&fuel_price=1500&co2_price=200&load=0.875 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 296, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 155, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'missing', 'loc': ('response', 'ac_route', 'max_tpd'), 'msg': 'Field required', 'input': {'route': {'pax_demand': {'y': 897, 'j': 539, 'f': 141}, 'cargo_demand': {'l': 449000, 'h': 539000}, 'direct_distance': 6481.05574647087}, 'warnings': [], 'valid': True, 'needs_stopover': False, 'stopover': {'exists': False}, 'flight_time': 5.956304550170898, 'trips_per_day_per_ac': 4, 'num_ac': 3, 'config': {'y': 43, 'j': 51, 'f': 13, 'algorithm': 'FJY'}, 'ticket': {'y': 3036, 'j': 6202, 'f': 9513}, 'max_income': 570519.0, 'income': 499204.125, 'fuel': 60921.96152767182, 'co2': 125321.07640124725, 'acheck_cost': 2215.6563829787233, 'repair_cost': 33.058935, 'profit': 380508.25211026415, 'ci': 200, 'contribution': 20.739377975463867}}
```

**Comment by cathaypacific8747** [comment]
Which version are you on? I am unable to reproduce the error.
```
curl "localhost:8002/ac_route/info?origin=iata%3AJFK&destination=iata%3AMUC&ac=name%3AB737-800&config_algorithm=AUTO&tpd_mode=STRICT_ALLOW_MULTIPLE_AC&trips_per_day_per_ac=4&sort_by=PER_AC_PER_DAY&realism=false&fuel_price=1500&co2_price=200&load=0.875" | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1541  100  1541    0     0  1381k      0 --:--:-- --:--:-- --:--:-- 1504k
{
  "status": "success",
  "ap_origin": {
    "id": 1427,
    "name": "New York JFK",
    "fullname": "John F Kennedy International Airport",
    "country": "United States",
    "continent": "North America",
    "iata": "JFK",
    "icao": "KJFK",
    "lat": 40.63980103,
    "lng": -73.77890015,
    "rwy": 14572,
    "market": 79,
    "hub_cost": 213300,
    "rwy_codes": "04L/22R|13L/31R"
  },
  "ap_destination": {
    "id": 460,
    "name": "Munich",
    "fullname": "Munich Airport",
    "country": "Germany",
    "continent": "Europe",
    "iata": "MUC",
    "icao": "EDDM",
    "lat": 48.353802,
    "lng": 11.7861,
    "rwy": 13123,
    "market": 74,
    "hub_cost": 213300,
    "rwy_codes": "08L/26R"
  },
  "ac": {
    "id": 3,
    "shortname": "b738",
    "manufacturer": "Boeing",
    "name": "B737-800",
    "type": "PAX",
    "priority": 0,
    "eid": 8,
    "ename": "CFM56-7B27",
    "speed": 725.4,
    "fuel": 9.4,
    "co2": 0.12,
    "cost": 4407858,
    "capacity": 184,
    "rwy": 7550,
    "check_cost": 231413,
    "range": 7000,
    "ceil": 40000,
    "maint": 470,
    "pilots": 2,
    "crew": 4,
    "engineers": 2,
    "technicians": 2,
    "img": "assets/img/aircraft/png/737.gif",
    "wingspan": 35,
    "length": 42,
    "speed_mod": false,
    "fuel_mod": false,
    "co2_mod": false,
    "fourx_mod": false
  },
  "ac_route": {
    "route": {
      "pax_demand": {
        "y": 897,
        "j": 539,
        "f": 141
      },
      "direct_distance": 6481.05574647087
    },
    "config": {
      "y": 43,
      "j": 51,
      "f": 13,
      "algorithm": "FJY"
    },
    "trips_per_day_per_ac": 4,
    "ticket": {
      "y": 3036,
      "j": 6202,
      "f": 9513
    },
    "max_income": 570519.0,
    "income": 499204.125,
    "fuel": 60921.96152767182,
    "co2": 125321.07640124725,
    "acheck_cost": 2215.6563829787233,
    "repair_cost": 33.058935,
    "profit": 380508.25211026415,
    "flight_time": 5.956304550170898,
    "num_ac": 3,
    "needs_stopover": false,
    "contribution": 20.739377975463867,
    "ci": 200,
    "stopover": {
      "exists": false
    },
    "warnings": [],
    "valid": true
  }
}
```

**Comment by Dexus** [comment]
just clones the repo and build the docker image like in the description

**Comment by Dexus** [comment]
with the fix it works, thanks.

**Comment by Dexus** [comment]
hi, there is still something wrong on the currend HEAD @cathaypacific8747 
```
INFO:     202.61.224.44:54916 - "GET /ac_route/info?origin=HKG&destination=CKY&ac=B737-800&config_algorithm=AUTO&max_flight_time=4&tpd_mode=STRICT_ALLOW_MULTIPLE_AC&trips_per_day_per_ac=3&sort_by=PER_AC_PER_DAY&fuel_price=1000&co2_price=150&accumulated_count=2&load=0.875 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 296, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 155, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'missing', 'loc': ('response', 'ac_route', 'max_tpd'), 'msg': 'Field required', 'input': {'route': {'pax_demand': {'y': 1046, 'j': 727, 'f': 157}, 'cargo_demand': {'l': 523000, 'h': 727000}, 'direct_distance': 13288.598804455238}, 'warnings': ['ERR_FLIGHT_TIME_ABOVE_SPECIFIED'], 'valid': False, 'needs_stopover': True, 'stopover': {'airport': {'id': 2450, 'name': 'Khorram Abad', 'fullname': 'Khoram Abad Airport', 'country': 'Iran', 'continent': 'Asia', 'iata': 'KHD', 'icao': 'OICK', 'lat': 33.43539810180664, 'lng': 48.282901763916016, 'rwy': 10498, 'market': 31, 'hub_cost': 6000, 'rwy_codes': '11/29'}, 'full_distance': 13288.781509015113, 'exists': True}, 'flight_time': 12.21282958984375}}

```

**Comment by Dexus** [comment]
Another one
```
INFO:     217.93.42.96:57342 - "GET /ac_route/info?origin=CHC&destination=HKG&ac=B737-800&tpd_mode=STRICT_ALLOW_MULTIPLE_AC&trips_per_day_per_ac=4&sort_by=PER_AC_PER_DAY&fuel_price=1250&co2_price=150&income_loss_tol=0.975&load=0.875 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 296, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 155, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'literal_error', 'loc': ('response', 'ac_route', 'warnings', 0), 'msg': "Input should be 'ERR_DISTANCE_ABOVE_SPECIFIED', 'ERR_DISTANCE_TOO_LONG', 'ERR_DISTANCE_TOO_SHORT', 'REDUCED_CONTRIBUTION', 'ERR_NO_STOPOVER', 'ERR_FLIGHT_TIME_ABOVE_SPECIFIED' or 'ERR_INSUFFICIENT_DEMAND'", 'input': 'ERR_TRIPS_PER_DAY_TOO_HIGH', 'ctx': {'expected': "'ERR_DISTANCE_ABOVE_SPECIFIED', 'ERR_DISTANCE_TOO_LONG', 'ERR_DISTANCE_TOO_SHORT', 'REDUCED_CONTRIBUTION', 'ERR_NO_STOPOVER', 'ERR_FLIGHT_TIME_ABOVE_SPECIFIED' or 'ERR_INSUFFICIENT_DEMAND'"}}

```
